import type { Metadata } from "next";
import { Figtree } from "next/font/google";

import "~/styles/globals.css";
import { cn } from "~/lib/utils";
import { Navbar } from "~/components/navbar";

const font = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(
          "min-h-screen font-sans antialiased grainy",
          font.className
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
